export const products = [
{
   id: 1,
   name: "Atomic Habits",
   slug: "atomic-habits",
   price: 150000,
   stock: 25,
   category: 3,
   category_name: "Pengembangan Diri",
   rating: 4.9,
   img: "src/assets/atomichabits.png",
},
{
   id: 2,
   name: "The Alchemist",
   slug: "the-alchemist",
   price: 120000,
   stock: 15,
   category: 2,
   category_name: "Novel",
   rating: 4.9,
   img: "src/assets/sangalkemis.png",
},
{
   id: 3,
   name: "Like The Flowing River",
   slug: "like-the-flowing-river",
   price: 95000,
   stock: 10,
   category: 1,
   category_name: "Novel",
   rating: 4.5,
   img: "src/assets/liketheflowing.png",
},
{
   id: 4,
   name: "Kalkulus Edisi 9",
   slug: "kalkulus",
   price: 250000,
   stock: 8,
   category: 1,
   category_name: "Pendidikan",
   rating: 4.2,
   img: "src/assets/kalkulus.png",
},
{
   id: 5,
   name: "Sapiens: Riwayat Singkat Umat Manusia",
   slug: "sapiens",
   price: 180000,
   stock: 12,
   category: 4,
   category_name: "Sejarah",
   rating: 4.7,
   img: "src/assets/sapiens.png",
},
{
   id: 6,
   name: "The Power of Habit",
   slug: "the-power-of-habit",
   price: 140000,
   stock: 20,
   category: 3,
   category_name: "Pengembangan Diri",
   rating: 4.6,
   img: "src/assets/tpohabit.png",
},
{
   id: 7,
   name: "Si Cacing dan Kotoran Kesayangannya 3",
   slug: "si-cacing-dan-kotoran-kesayangannya",
   price: 120000,
   stock: 6,
   category: 1,
   category_name: "Novel",
   rating: 4.8,
   img: "src/assets/sicacing.png",
}
];